version: "3"
services:
  teste_fidelizi_api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: teste_fidelizi_api
    volumes:
      - .:/var/www/app
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 3000:80
    depends_on: 
      - teste_fidelizi_db
  teste_fidelizi_db:
    container_name: teste_fidelizi_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=loyalty